name: teamviewer-snap
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Teamviewer as a snap for installation in Ubuntu Core 18
description: |
  Install Teamviewer in headless mode at Ubuntu Core 18 which only
  snaps and no regular debian packages.
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
